import { Stack, RemovalPolicy, Duration, CfnOutput, Fn, type StackProps } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as sm from 'aws-cdk-lib/aws-secretsmanager';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as cw from 'aws-cdk-lib/aws-cloudwatch';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import type { Construct } from 'constructs';

export type LinkbioStackProps = StackProps & {
  /** An external issuer's JWKS. Omit to have the API issue its own tokens. */
  jwksUrl?: string;
  jwtIssuer?: string;
  jwtAudience?: string;
  /** Exact browser origins allowed to call the API cross-origin. */
  corsOrigins?: string[];
  /**
   * Credentials for the feed sources that have no anonymous read path, as
   * Secrets Manager ARNs. Omitting one leaves that source reporting itself
   * unconfigured at refresh time rather than failing the deploy — a stack with
   * no Spotify blocks should not be made to hold Spotify credentials.
   */
  spotifySecretArn?: string;
  twitchSecretArn?: string;
  /** Raises the GitHub adapter from 60 requests an hour to 5,000. */
  githubTokenSecretArn?: string;
  /** How often the feed refresher runs. Defaults to every five minutes. */
  refreshRate?: Duration;
  /**
   * The built Next app: the directory `web/scripts/package-lambda.mjs` writes.
   * Relative to `api/`, because that is where `cdk.json` runs.
   */
  webAssetPath?: string;
  /** Memory for the web Lambda. 1769 MB is one full vCPU, which is what SSR cold starts respond to. */
  webMemorySize?: number;
  /**
   * A shared secret CloudFront sends to both origins as `x-origin-secret`, and
   * both origins require.
   *
   * The function URLs are `authType: NONE`, which is not a preference: Origin
   * Access Control signs origin requests, and a signed request to a Lambda
   * function URL must carry the SHA-256 of its own body in
   * `x-amz-content-sha256` — computed by the *viewer*, because CloudFront does
   * not hash the body for you, and Lambda rejects `UNSIGNED-PAYLOAD`. A browser
   * cannot do that, so under OAC every form post, every Server Action and every
   * click beacon is a 403. AWS documents this; it is why nothing serving a
   * browser puts OAC in front of a function URL.
   *
   * What is left to keep the function URLs from being an open back door past
   * the WAF is a secret CloudFront adds and viewers cannot: a custom origin
   * header overwrites any header of the same name from the viewer.
   *
   * Omitting it deploys a stack whose function URLs answer anyone who finds
   * them. The app's own auth still applies; the WAF's rate limit and managed
   * rules do not. Generate one with `openssl rand -hex 32` and pass it as
   * `-c originSecret=…`.
   */
  originSecret?: string;
  /**
   * Concurrent executions to reserve for the feed refresher. **Off by default.**
   *
   * Reserving one would stop two runs overlapping and doubling the rate-limit
   * pressure on YouTube and GitHub. That is worth having, and it is not worth
   * an undeployable stack: a reservation must leave at least 10 unreserved
   * concurrent executions in the account, and a new AWS account's *entire*
   * limit is 10 — so reserving even one is rejected outright. That is the
   * account's limit talking, not this function's, and the error
   * ("decreases account's UnreservedConcurrentExecution below its minimum
   * value") does not say so.
   *
   * Nothing depends on the reservation for correctness. The refresher is
   * idempotent by construction — the work list is a due-time index and the
   * first thing each refresh does is push that time forward — so two runs
   * duplicate a fetch and corrupt nothing.
   *
   * Set it to 1 once the account's concurrency limit has been raised.
   */
  refresherReservedConcurrency?: number;
};

export class LinkbioStack extends Stack {
  constructor(scope: Construct, id: string, props?: LinkbioStackProps) {
    super(scope, id, props);

    // Generated by CloudFormation and never in source or in a template
    // parameter. The env schema rejects anything under 32 bytes.
    const authSecret = new sm.Secret(this, 'AuthSecret', {
      description: 'HS256 signing key for the tokens the API issues',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'secret',
        passwordLength: 64,
        excludePunctuation: true,
      },
    });

    // ---------- data ----------

    const table = new dynamodb.TableV2(this, 'Table', {
      partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
      billing: dynamodb.Billing.onDemand(),
      timeToLiveAttribute: 'ttl',
      dynamoStream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
      removalPolicy: RemovalPolicy.RETAIN,
      globalSecondaryIndexes: [
        {
          indexName: 'GSI1',
          partitionKey: { name: 'GSI1PK', type: dynamodb.AttributeType.STRING },
          sortKey: { name: 'GSI1SK', type: dynamodb.AttributeType.STRING },
        },
        {
          // Sparse on purpose: only feed blocks carry GSI2PK, so the index holds
          // refreshable blocks and nothing else.
          indexName: 'GSI2',
          partitionKey: { name: 'GSI2PK', type: dynamodb.AttributeType.STRING },
          sortKey: { name: 'GSI2SK', type: dynamodb.AttributeType.NUMBER },
          projectionType: dynamodb.ProjectionType.ALL,
        },
      ],
    });

    // ---------- edge config ----------

    const kvs = new cloudfront.KeyValueStore(this, 'RoutingConfig', {
      comment: 'Per-handle cache-key masks and hot links',
    });

    const normalizer = new cloudfront.Function(this, 'CtxNormalizer', {
      runtime: cloudfront.FunctionRuntime.JS_2_0, // required for KeyValueStore access
      keyValueStore: kvs,
      code: cloudfront.FunctionCode.fromFile({ filePath: 'edge/normalize.js' }),
    });

    // ---------- api ----------

    // CloudWatch keeps logs forever by default, which is a slow-growing bill
    // for data nobody reads after a fortnight.
    const logGroup = new logs.LogGroup(this, 'ApiLogs', {
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const api = new lambda.Function(this, 'Api', {
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.ARM_64, // ~20% cheaper per GB-second
      handler: 'index.handler',
      code: lambda.Code.fromAsset('dist'),
      memorySize: 1024,
      timeout: Duration.seconds(10),
      logGroup,
      deadLetterQueueEnabled: true,
      environment: {
        TABLE_NAME: table.tableName,
        KVS_ARN: kvs.keyValueStoreArn,
        NODE_ENV: 'production',
        NODE_OPTIONS: '--enable-source-maps',
        // Without one of these every authenticated request is a 401, and the
        // env schema now refuses to boot rather than serving a dead control
        // plane. The stack previously set neither.
        AUTH_SECRET: authSecret.secretValueFromJson('secret').unsafeUnwrap(),
        ...(props?.jwksUrl
          ? { JWKS_URL: props.jwksUrl, JWT_ISSUER: props.jwtIssuer ?? '', JWT_AUDIENCE: props.jwtAudience ?? '' }
          : {}),
        CORS_ORIGINS: (props?.corsOrigins ?? []).join(','),
        ...(props?.originSecret ? { ORIGIN_SECRET: props.originSecret } : {}),
      },
      // Deliberately not in a VPC. DynamoDB and CloudFront are reached over the
      // public AWS endpoints, so attaching one would only add a NAT gateway at
      // ~$33/month before a single request is served.
    });

    table.grantReadWriteData(api);
    // `UpdateKeys`, not `PutKey`/`DeleteKey`. The batch API is its own IAM
    // action, and it is the only one `publish.ts` ever calls — puts and deletes
    // must land in one all-or-nothing call or the edge can see a half-published
    // profile. Granting the single-key actions instead denied every publish,
    // which surfaced as a 500 on every block create, not as a permissions
    // error, because the publish is downstream of the write that succeeded.
    api.addToRolePolicy(new iam.PolicyStatement({
      actions: [
        'cloudfront-keyvaluestore:DescribeKeyValueStore',
        'cloudfront-keyvaluestore:UpdateKeys',
      ],
      resources: [kvs.keyValueStoreArn],
    }));

    // AWS_IAM plus OAC is the tempting shape and it does not work for anything
    // a browser posts to — see `originSecret` above.
    const fnUrl = api.addFunctionUrl({ authType: lambda.FunctionUrlAuthType.NONE });

    // ---------- feed refresher ----------
    //
    // Its own function rather than a route on the API. It waits on five third
    // parties, so it needs a timeout six times the API's; and a feed that hangs
    // must not be able to eat the concurrency a creator's dashboard is using.
    //
    // Idempotent by construction — the work list is a due-time index and the
    // first thing each refresh does is push that time forward — so EventBridge
    // firing twice duplicates a fetch and corrupts nothing.

    const spotify = props?.spotifySecretArn
      ? sm.Secret.fromSecretCompleteArn(this, 'SpotifySecret', props.spotifySecretArn)
      : undefined;
    const twitch = props?.twitchSecretArn
      ? sm.Secret.fromSecretCompleteArn(this, 'TwitchSecret', props.twitchSecretArn)
      : undefined;
    const githubToken = props?.githubTokenSecretArn
      ? sm.Secret.fromSecretCompleteArn(this, 'GithubTokenSecret', props.githubTokenSecretArn)
      : undefined;

    const refresher = new lambda.Function(this, 'FeedRefresher', {
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.ARM_64,
      handler: 'index.handler',
      code: lambda.Code.fromAsset('dist-refresher'),
      memorySize: 512,
      timeout: Duration.seconds(60),
      logGroup: new logs.LogGroup(this, 'FeedRefresherLogs', {
        retention: logs.RetentionDays.ONE_MONTH,
        removalPolicy: RemovalPolicy.DESTROY,
      }),
      // Unreserved unless asked for — see the prop. Overlapping runs are
      // wasteful rather than wrong.
      ...(props?.refresherReservedConcurrency
        ? { reservedConcurrentExecutions: props.refresherReservedConcurrency }
        : {}),
      deadLetterQueueEnabled: true,
      environment: {
        TABLE_NAME: table.tableName,
        NODE_ENV: 'production',
        NODE_OPTIONS: '--enable-source-maps',
        // The refresher issues no tokens and verifies none, but `env.ts` parses
        // one schema for the whole codebase and refuses to boot without a
        // signing secret. Sharing the API's costs nothing and keeps the config
        // contract in one place.
        AUTH_SECRET: authSecret.secretValueFromJson('secret').unsafeUnwrap(),
        ...(spotify
          ? {
              SPOTIFY_CLIENT_ID: spotify.secretValueFromJson('clientId').unsafeUnwrap(),
              SPOTIFY_CLIENT_SECRET: spotify.secretValueFromJson('clientSecret').unsafeUnwrap(),
            }
          : {}),
        ...(twitch
          ? {
              TWITCH_CLIENT_ID: twitch.secretValueFromJson('clientId').unsafeUnwrap(),
              TWITCH_CLIENT_SECRET: twitch.secretValueFromJson('clientSecret').unsafeUnwrap(),
            }
          : {}),
        ...(githubToken ? { GITHUB_TOKEN: githubToken.secretValueFromJson('token').unsafeUnwrap() } : {}),
      },
    });

    table.grantReadWriteData(refresher);

    new events.Rule(this, 'FeedRefreshSchedule', {
      description: 'Fills feed blocks whose TTL has elapsed',
      schedule: events.Schedule.rate(props?.refreshRate ?? Duration.minutes(5)),
      targets: [new targets.LambdaFunction(refresher, { retryAttempts: 0 })],
    });

    // ---------- web ----------
    //
    // The Next app, as the distribution's default origin.
    //
    // It was not an origin in this stack at all before: the default behaviour
    // pointed at the API, so the dashboard had nowhere to be served from and
    // `/r/*` was answered by a route handler inside Next — which put the Next
    // Lambda in the click path, the one thing the edge hot-link short-circuit
    // exists to avoid. With the web app as the default and `/r/*`, `/p/*`,
    // `/v1/*` and `/health` as behaviours on the API, a click never reaches it
    // and `HOT_LINKS` becomes reachable for the first time.

    const webFn = new lambda.Function(this, 'Web', {
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.ARM_64,
      // `lambda/handler.mjs`, copied to the root of the bundle beside Next's
      // standalone `server.js`.
      handler: 'handler.handler',
      code: lambda.Code.fromAsset(props?.webAssetPath ?? '../web/dist'),
      // Server rendering is CPU-bound and Lambda scales CPU with memory: 1769 MB
      // is one full vCPU, and it is cold starts rather than steady-state cost
      // that this buys down. Below ~1 GB the first render of the dashboard is
      // measured in seconds.
      memorySize: props?.webMemorySize ?? 1769,
      // Longer than the API's 10s so a slow upstream surfaces as the API's
      // timeout, with a 503 the page can render, rather than as this one's.
      timeout: Duration.seconds(15),
      logGroup: new logs.LogGroup(this, 'WebLogs', {
        retention: logs.RetentionDays.ONE_MONTH,
        removalPolicy: RemovalPolicy.DESTROY,
      }),
      environment: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--enable-source-maps',
        // Host only: `FunctionUrl.url` ends in a slash and every path this app
        // builds starts with one, which would make every request `//v1/...`.
        API_ORIGIN: Fn.join('', ['https://', Fn.select(2, Fn.split('/', fnUrl.url))]),
        // Presented on every server-side call to the API, which goes direct
        // rather than back through the CDN. See web/src/lib/api/origin-fetch.ts.
        ...(props?.originSecret ? { ORIGIN_SECRET: props.originSecret } : {}),
        // Read at request time (it is not a NEXT_PUBLIC_ value, so it is not
        // baked into the build). Must not exceed the cache policy's maxTtl.
        MAX_S_MAXAGE: '3600',
      },
    });

    const webFnUrl = webFn.addFunctionUrl({ authType: lambda.FunctionUrlAuthType.NONE });

    // ---------- distribution ----------

    // x-ctx is the only header in the cache key. Everything the origin varies on
    // is folded into it by the edge function, which keeps cardinality bounded.
    const redirectCache = new cloudfront.CachePolicy(this, 'RedirectCache', {
      headerBehavior: cloudfront.CacheHeaderBehavior.allowList('x-ctx'),
      queryStringBehavior: cloudfront.CacheQueryStringBehavior.none(),
      cookieBehavior: cloudfront.CacheCookieBehavior.none(),
      defaultTtl: Duration.seconds(60),
      minTtl: Duration.seconds(0),
      // Must exceed the API's MAX_S_MAXAGE or CloudFront silently truncates
      // every TTL the rule evaluator computes.
      maxTtl: Duration.hours(24),
      enableAcceptEncodingGzip: true,
    });

    // The origin still needs the raw viewer signals to compute the right answer
    // even though they are not part of the cache key.
    const originRequest = new cloudfront.OriginRequestPolicy(this, 'OriginRequest', {
      headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
        'x-ctx', 'cloudfront-viewer-country', 'cloudfront-is-mobile-viewer',
        'cloudfront-is-tablet-viewer', 'user-agent', 'referer', 'accept-language',
      ),
      queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
      cookieBehavior: cloudfront.OriginRequestCookieBehavior.none(),
    });

    // `authorization` is deliberately absent: CloudFront refuses to forward it
    // through an origin request policy, and OAC would overwrite it with its own
    // SigV4 signature anyway. `edge/auth-header.js` copies it to
    // `x-authorization`, which is what the origin reads.
    const controlPlaneRequest = new cloudfront.OriginRequestPolicy(this, 'ControlPlaneRequest', {
      headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
        'x-authorization', 'content-type', 'if-match', 'origin', 'referer',
        'cloudfront-viewer-address', 'user-agent',
      ),
      queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
      cookieBehavior: cloudfront.OriginRequestCookieBehavior.none(),
    });

    const authHeader = new cloudfront.Function(this, 'AuthHeader', {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromFile({ filePath: 'edge/auth-header.js' }),
    });

    /**
     * The public page on the web origin. Same shape as `originRequest` — the
     * origin needs the raw viewer signals even though only `x-ctx` is in the
     * key — plus the viewer's host, which a Lambda function URL origin never
     * sees for itself because OAC signs against the origin's own hostname.
     */
    const pageRequest = new cloudfront.OriginRequestPolicy(this, 'PageRequest', {
      headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
        'x-ctx', 'x-forwarded-host', 'cloudfront-viewer-country',
        'cloudfront-is-mobile-viewer', 'cloudfront-is-tablet-viewer',
        'user-agent', 'referer', 'accept-language',
      ),
      queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
      // The public page is cached and must never vary on a cookie.
      cookieBehavior: cloudfront.OriginRequestCookieBehavior.none(),
    });

    /**
     * The dashboard, sign-in and the proxy.
     *
     * The managed all-viewer policy rather than an allowlist, for two reasons.
     *
     * An allowlist is capped at ten headers and this surface needs more than
     * ten: cookies carry the session, `origin` is the CSRF check, `if-match` is
     * the version conflict, `content-type` is every form post, and the App
     * Router needs `rsc`, `next-action`, `next-router-state-tree`,
     * `next-router-prefetch` and `next-url` or client navigation and Server
     * Actions quietly stop working. The first deploy failed on exactly that
     * quota.
     *
     * And the reason an allowlist was reached for in the first place no longer
     * applies: it was to keep `Authorization` away from Origin Access Control's
     * own signature, and there is no OAC here any more.
     */
    const appRequest = cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER;

    const pageNormalizer = new cloudfront.Function(this, 'PageNormalizer', {
      runtime: cloudfront.FunctionRuntime.JS_2_0, // required for KeyValueStore access
      keyValueStore: kvs,
      code: cloudfront.FunctionCode.fromFile({ filePath: 'edge/page.js' }),
    });

    // Rate limiting has to live somewhere the whole fleet can see. The
    // in-process counters on the beacon and the credential endpoints bound what
    // one warm container will do, which is not the same thing.
    const acl = new wafv2.CfnWebACL(this, 'Waf', {
      scope: 'CLOUDFRONT',
      defaultAction: { allow: {} },
      visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'linkbio-waf', sampledRequestsEnabled: true },
      rules: [
        {
          name: 'beacon-and-auth-rate',
          priority: 0,
          action: { block: {} },
          statement: {
            rateBasedStatement: {
              limit: 2000, // per 5 minutes, per source IP
              aggregateKeyType: 'IP',
              scopeDownStatement: {
                byteMatchStatement: {
                  searchString: '/v1/',
                  fieldToMatch: { uriPath: {} },
                  positionalConstraint: 'STARTS_WITH',
                  textTransformations: [{ priority: 0, type: 'LOWERCASE' }],
                },
              },
            },
          },
          visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'rate', sampledRequestsEnabled: true },
        },
        {
          name: 'common',
          priority: 1,
          overrideAction: { none: {} },
          statement: {
            managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesCommonRuleSet' },
          },
          visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'common', sampledRequestsEnabled: true },
        },
      ],
    });

    // Sent by CloudFront, never by a viewer: a custom origin header overwrites
    // a viewer header of the same name. Both Lambdas refuse a request without
    // it when ORIGIN_SECRET is set.
    const customHeaders = props?.originSecret ? { 'x-origin-secret': props.originSecret } : undefined;

    const apiOrigin = new origins.FunctionUrlOrigin(fnUrl, {
      customHeaders,
      readTimeout: Duration.seconds(10),
      // The architecture deliberately aligns every edge location's TTL to the
      // same rule boundary, so they all expire in the same instant and all miss
      // at once. Origin Shield is the one mitigation that design requires, and
      // it was described in the README and then never configured.
      originShieldEnabled: true,
      originShieldRegion: this.region,
    });

    const webOrigin = new origins.FunctionUrlOrigin(webFnUrl, {
      customHeaders,
      readTimeout: Duration.seconds(15),
      originShieldEnabled: true,
      originShieldRegion: this.region,
    });

    /** `/r/*` and `/p/*`: the API's cached public surface. */
    const redirectBehavior = {
      origin: apiOrigin,
      cachePolicy: redirectCache,
      originRequestPolicy: originRequest,
      functionAssociations: [{
        function: normalizer,
        eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
      }],
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    };

    /**
     * The default: the Next app, serving `/<handle>` at the root.
     *
     * Cached on `x-ctx` exactly as the API's public routes are, and for the same
     * reason — the page's content depends on the viewer, so the key must too.
     * `edge/page.js` writes that header; `web/src/app/[handle]/route.ts` decodes
     * it and answers as a function of it and nothing else.
     */
    const pageBehavior = {
      origin: webOrigin,
      cachePolicy: redirectCache,
      originRequestPolicy: pageRequest,
      functionAssociations: [{
        function: pageNormalizer,
        eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
      }],
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    };

    /**
     * The dashboard, sign-in and the token proxy: per-user, cookie-bearing, and
     * never cached anywhere.
     *
     * `HTTPS_ONLY` rather than `REDIRECT_TO_HTTPS`: a redirect turns a POST into
     * a GET and loses its body, and every write in this app is a POST.
     */
    const appBehavior = {
      origin: webOrigin,
      cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
      originRequestPolicy: appRequest,
      allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
      functionAssociations: [{
        function: pageNormalizer,
        eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
      }],
    };

    const dist = new cloudfront.Distribution(this, 'Cdn', {
      defaultBehavior: pageBehavior,
      // Order matters: CloudFront takes the first pattern that matches, not the
      // most specific one. `/_next/static/*` has to precede `/_next/*`, and the
      // dashboard paths have to precede the default, which would otherwise
      // treat `/login` as a creator's handle.
      additionalBehaviors: {
        /**
         * Content-hashed filenames, so they are immutable and the managed
         * optimized policy's long TTL is safe. This is the one web behaviour
         * that should essentially never reach the origin twice.
         */
        '/_next/static/*': {
          origin: webOrigin,
          cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
          // No origin request policy: a content-hashed asset depends on nothing
          // about the viewer, and forwarding anything would only add cache keys.
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        },
        // The image optimizer and RSC payloads. Uncached rather than wrong.
        '/_next/*': appBehavior,
        // `/app` exactly, and then everything under it. Not `/app*`, which also
        // matches `/apple` — a handle nobody has reserved.
        '/app': appBehavior,
        '/app/*': appBehavior,
        '/login': appBehavior,
        '/signup': appBehavior,
        '/logout': appBehavior,
        '/api/proxy/*': appBehavior,
        // The click redirector and the JSON resolution, both on the API. This
        // is the routing that makes the edge hot-link short-circuit reachable:
        // a click never wakes the Next Lambda.
        '/r/*': redirectBehavior,
        '/p/*': redirectBehavior,
        // The control plane is per-user and must never be cached.
        //
        // Still an explicit allowlist, and still carrying the bearer in
        // `x-authorization`: CloudFront refuses `Authorization` in an origin
        // request policy allowlist at all, and `edge/auth-header.js` copies it
        // to a name it does not claim. `api/src/auth.ts` reads that first and
        // falls back to `authorization`, so calling the origin directly in
        // development still works.
        '/v1/*': {
          origin: apiOrigin,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: controlPlaneRequest,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
          functionAssociations: [{
            function: authHeader,
            eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
          }],
        },
        '/health': {
          origin: apiOrigin,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        },
      },
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
      webAclId: acl.attrArn,
      enableLogging: true,
    });

    // ---------- alarms ----------
    //
    // The three places the code deliberately keeps going after a failure — the
    // mask publish, click accounting and the event beacon — are exactly the
    // three that need a counter, because nothing else will ever tell you.

    const alarm = (id: string, metric: cw.IMetric, threshold: number, reason: string) =>
      new cw.Alarm(this, id, {
        metric, threshold, evaluationPeriods: 2,
        comparisonOperator: cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cw.TreatMissingData.NOT_BREACHING,
        alarmDescription: reason,
      });

    alarm('ApiErrors', api.metricErrors({ period: Duration.minutes(5) }), 5,
      'The API is throwing. Unhandled errors are logged with a requestId.');
    alarm('ApiThrottles', api.metricThrottles({ period: Duration.minutes(5) }), 0,
      'Concurrency limit reached — requests are being rejected before they run.');
    alarm('Api5xx', dist.metric5xxErrorRate({ period: Duration.minutes(5) }), 1,
      'CloudFront is serving 5xx for more than 1% of requests.');
    alarm('WebErrors', webFn.metricErrors({ period: Duration.minutes(5) }), 5,
      'The web app is throwing. A 500 here is a creator page or a dashboard route, not a click.');
    alarm('WebThrottles', webFn.metricThrottles({ period: Duration.minutes(5) }), 0,
      'The web app hit its concurrency limit — requests are rejected before they run.');
    alarm('FeedRefresherErrors', refresher.metricErrors({ period: Duration.minutes(15) }), 2,
      'The feed refresher is throwing. Individual feed failures are backed off per block and logged, '
      + 'not thrown, so this means the loop itself is broken.');

    new CfnOutput(this, 'AuthSecretArn', { value: authSecret.secretArn });
    new CfnOutput(this, 'DistributionDomain', { value: dist.distributionDomainName });
    new CfnOutput(this, 'TableName', { value: table.tableName });
    new CfnOutput(this, 'KvsArn', { value: kvs.keyValueStoreArn });
    new CfnOutput(this, 'FeedRefresherName', { value: refresher.functionName });
    new CfnOutput(this, 'WebFunctionName', { value: webFn.functionName });
    new CfnOutput(this, 'SiteUrl', { value: `https://${dist.distributionDomainName}` });
  }
}
