import { Stack, RemovalPolicy, Duration, CfnOutput, type StackProps } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as sm from 'aws-cdk-lib/aws-secretsmanager';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as cw from 'aws-cdk-lib/aws-cloudwatch';
import type { Construct } from 'constructs';

export type LinkbioStackProps = StackProps & {
  /** An external issuer's JWKS. Omit to have the API issue its own tokens. */
  jwksUrl?: string;
  jwtIssuer?: string;
  jwtAudience?: string;
  /** Exact browser origins allowed to call the API cross-origin. */
  corsOrigins?: string[];
};

export class LinkbioStack extends Stack {
  constructor(scope: Construct, id: string, props?: LinkbioStackProps) {
    super(scope, id, props);

    // Generated by CloudFormation and never in source or in a template
    // parameter. The env schema rejects anything under 32 bytes.
    const authSecret = new sm.Secret(this, 'AuthSecret', {
      description: 'HS256 signing key for the tokens the API issues',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'secret',
        passwordLength: 64,
        excludePunctuation: true,
      },
    });

    // ---------- data ----------

    const table = new dynamodb.TableV2(this, 'Table', {
      partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
      billing: dynamodb.Billing.onDemand(),
      timeToLiveAttribute: 'ttl',
      dynamoStream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
      removalPolicy: RemovalPolicy.RETAIN,
      globalSecondaryIndexes: [
        {
          indexName: 'GSI1',
          partitionKey: { name: 'GSI1PK', type: dynamodb.AttributeType.STRING },
          sortKey: { name: 'GSI1SK', type: dynamodb.AttributeType.STRING },
        },
        {
          // Sparse on purpose: only feed blocks carry GSI2PK, so the index holds
          // refreshable blocks and nothing else.
          indexName: 'GSI2',
          partitionKey: { name: 'GSI2PK', type: dynamodb.AttributeType.STRING },
          sortKey: { name: 'GSI2SK', type: dynamodb.AttributeType.NUMBER },
          projectionType: dynamodb.ProjectionType.ALL,
        },
      ],
    });

    // ---------- edge config ----------

    const kvs = new cloudfront.KeyValueStore(this, 'RoutingConfig', {
      comment: 'Per-handle cache-key masks and hot links',
    });

    const normalizer = new cloudfront.Function(this, 'CtxNormalizer', {
      runtime: cloudfront.FunctionRuntime.JS_2_0, // required for KeyValueStore access
      keyValueStore: kvs,
      code: cloudfront.FunctionCode.fromFile({ filePath: 'edge/normalize.js' }),
    });

    // ---------- api ----------

    // CloudWatch keeps logs forever by default, which is a slow-growing bill
    // for data nobody reads after a fortnight.
    const logGroup = new logs.LogGroup(this, 'ApiLogs', {
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const api = new lambda.Function(this, 'Api', {
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.ARM_64, // ~20% cheaper per GB-second
      handler: 'index.handler',
      code: lambda.Code.fromAsset('dist'),
      memorySize: 1024,
      timeout: Duration.seconds(10),
      logGroup,
      deadLetterQueueEnabled: true,
      environment: {
        TABLE_NAME: table.tableName,
        KVS_ARN: kvs.keyValueStoreArn,
        NODE_ENV: 'production',
        NODE_OPTIONS: '--enable-source-maps',
        // Without one of these every authenticated request is a 401, and the
        // env schema now refuses to boot rather than serving a dead control
        // plane. The stack previously set neither.
        AUTH_SECRET: authSecret.secretValueFromJson('secret').unsafeUnwrap(),
        ...(props?.jwksUrl
          ? { JWKS_URL: props.jwksUrl, JWT_ISSUER: props.jwtIssuer ?? '', JWT_AUDIENCE: props.jwtAudience ?? '' }
          : {}),
        CORS_ORIGINS: (props?.corsOrigins ?? []).join(','),
      },
      // Deliberately not in a VPC. DynamoDB and CloudFront are reached over the
      // public AWS endpoints, so attaching one would only add a NAT gateway at
      // ~$33/month before a single request is served.
    });

    table.grantReadWriteData(api);
    api.addToRolePolicy(new iam.PolicyStatement({
      actions: [
        'cloudfront-keyvaluestore:DescribeKeyValueStore',
        'cloudfront-keyvaluestore:PutKey',
        'cloudfront-keyvaluestore:DeleteKey',
      ],
      resources: [kvs.keyValueStoreArn],
    }));

    const fnUrl = api.addFunctionUrl({ authType: lambda.FunctionUrlAuthType.AWS_IAM });

    // ---------- distribution ----------

    // x-ctx is the only header in the cache key. Everything the origin varies on
    // is folded into it by the edge function, which keeps cardinality bounded.
    const redirectCache = new cloudfront.CachePolicy(this, 'RedirectCache', {
      headerBehavior: cloudfront.CacheHeaderBehavior.allowList('x-ctx'),
      queryStringBehavior: cloudfront.CacheQueryStringBehavior.none(),
      cookieBehavior: cloudfront.CacheCookieBehavior.none(),
      defaultTtl: Duration.seconds(60),
      minTtl: Duration.seconds(0),
      // Must exceed the API's MAX_S_MAXAGE or CloudFront silently truncates
      // every TTL the rule evaluator computes.
      maxTtl: Duration.hours(24),
      enableAcceptEncodingGzip: true,
    });

    // The origin still needs the raw viewer signals to compute the right answer
    // even though they are not part of the cache key.
    const originRequest = new cloudfront.OriginRequestPolicy(this, 'OriginRequest', {
      headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
        'x-ctx', 'cloudfront-viewer-country', 'cloudfront-is-mobile-viewer',
        'cloudfront-is-tablet-viewer', 'user-agent', 'referer', 'accept-language',
      ),
      queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
      cookieBehavior: cloudfront.OriginRequestCookieBehavior.none(),
    });

    // `authorization` is deliberately absent: CloudFront refuses to forward it
    // through an origin request policy, and OAC would overwrite it with its own
    // SigV4 signature anyway. `edge/auth-header.js` copies it to
    // `x-authorization`, which is what the origin reads.
    const controlPlaneRequest = new cloudfront.OriginRequestPolicy(this, 'ControlPlaneRequest', {
      headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
        'x-authorization', 'content-type', 'if-match', 'origin', 'referer',
        'cloudfront-viewer-address', 'user-agent',
      ),
      queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
      cookieBehavior: cloudfront.OriginRequestCookieBehavior.none(),
    });

    const authHeader = new cloudfront.Function(this, 'AuthHeader', {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromFile({ filePath: 'edge/auth-header.js' }),
    });

    // Rate limiting has to live somewhere the whole fleet can see. The
    // in-process counters on the beacon and the credential endpoints bound what
    // one warm container will do, which is not the same thing.
    const acl = new wafv2.CfnWebACL(this, 'Waf', {
      scope: 'CLOUDFRONT',
      defaultAction: { allow: {} },
      visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'linkbio-waf', sampledRequestsEnabled: true },
      rules: [
        {
          name: 'beacon-and-auth-rate',
          priority: 0,
          action: { block: {} },
          statement: {
            rateBasedStatement: {
              limit: 2000, // per 5 minutes, per source IP
              aggregateKeyType: 'IP',
              scopeDownStatement: {
                byteMatchStatement: {
                  searchString: '/v1/',
                  fieldToMatch: { uriPath: {} },
                  positionalConstraint: 'STARTS_WITH',
                  textTransformations: [{ priority: 0, type: 'LOWERCASE' }],
                },
              },
            },
          },
          visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'rate', sampledRequestsEnabled: true },
        },
        {
          name: 'common',
          priority: 1,
          overrideAction: { none: {} },
          statement: {
            managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesCommonRuleSet' },
          },
          visibilityConfig: { cloudWatchMetricsEnabled: true, metricName: 'common', sampledRequestsEnabled: true },
        },
      ],
    });

    const origin = origins.FunctionUrlOrigin.withOriginAccessControl(fnUrl, {
      readTimeout: Duration.seconds(10),
      // The architecture deliberately aligns every edge location's TTL to the
      // same rule boundary, so they all expire in the same instant and all miss
      // at once. Origin Shield is the one mitigation that design requires, and
      // it was described in the README and then never configured.
      originShieldEnabled: true,
      originShieldRegion: this.region,
    });

    const behavior = {
      origin,
      cachePolicy: redirectCache,
      originRequestPolicy: originRequest,
      functionAssociations: [{
        function: normalizer,
        eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
      }],
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    };

    const dist = new cloudfront.Distribution(this, 'Cdn', {
      defaultBehavior: behavior,
      additionalBehaviors: {
        '/r/*': behavior,
        '/p/*': behavior,
        // The control plane is per-user and must never be cached.
        //
        // ALL_VIEWER_EXCEPT_HOST_HEADER forwards the viewer's Authorization
        // header, and OAC signs the origin request with SigV4 using that same
        // header — the two collide, and the Lambda sees CloudFront's signature
        // instead of the caller's bearer token. Forwarding an explicit list and
        // carrying the bearer in its own header avoids the conflict.
        '/v1/*': {
          origin,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: controlPlaneRequest,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
          functionAssociations: [{
            function: authHeader,
            eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
          }],
        },
      },
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
      webAclId: acl.attrArn,
      enableLogging: true,
    });

    // ---------- alarms ----------
    //
    // The three places the code deliberately keeps going after a failure — the
    // mask publish, click accounting and the event beacon — are exactly the
    // three that need a counter, because nothing else will ever tell you.

    const alarm = (id: string, metric: cw.IMetric, threshold: number, reason: string) =>
      new cw.Alarm(this, id, {
        metric, threshold, evaluationPeriods: 2,
        comparisonOperator: cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cw.TreatMissingData.NOT_BREACHING,
        alarmDescription: reason,
      });

    alarm('ApiErrors', api.metricErrors({ period: Duration.minutes(5) }), 5,
      'The API is throwing. Unhandled errors are logged with a requestId.');
    alarm('ApiThrottles', api.metricThrottles({ period: Duration.minutes(5) }), 0,
      'Concurrency limit reached — requests are being rejected before they run.');
    alarm('Api5xx', dist.metric5xxErrorRate({ period: Duration.minutes(5) }), 1,
      'CloudFront is serving 5xx for more than 1% of requests.');

    new CfnOutput(this, 'AuthSecretArn', { value: authSecret.secretArn });
    new CfnOutput(this, 'DistributionDomain', { value: dist.distributionDomainName });
    new CfnOutput(this, 'TableName', { value: table.tableName });
    new CfnOutput(this, 'KvsArn', { value: kvs.keyValueStoreArn });
  }
}
